swagger: '2.0'
info:
  title: Panopto Public Accessibility CaptionProviders API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
host: <PanoptoServerURL>(i.e. example.hosted.panopto.com)
basePath: /Panopto
schemes:
- https
consumes:
- application/json
produces:
- application/json
tags:
- name: CaptionProviders
  description: Caption Providers API
paths:
  /api/v1/captionproviders:
    get:
      tags:
      - CaptionProviders
      summary: Get caption providers
      description: To fetch all elements, this endpoint can be called multiple times, starting at pageNumber = 0 and incrementing the page number until no results are returned.
      operationId: CaptionProviders_GetCaptionProviders
      parameters:
      - type: string
        name: sortField
        in: query
        x-schema:
          $ref: '#/definitions/TranscriptionProviderInstanceSortFields'
        default: Name
        x-nullable: false
        enum:
        - Name
      - type: string
        name: sortOrder
        in: query
        x-schema:
          $ref: '#/definitions/SortOrder'
        default: Asc
        x-nullable: false
        enum:
        - Asc
        - Desc
      - type: integer
        name: pageNumber
        in: query
        format: int32
        default: 0
        x-nullable: false
      responses:
        '200':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/ListResponseOfTranscriptionProviderInstance'
        '400':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
definitions:
  TranscriptionProviderInstance:
    allOf:
    - $ref: '#/definitions/ModelBaseOfGuid'
    - type: object
      required:
      - Enabled
      properties:
        Enabled:
          type: boolean
        DisplayName:
          type: string
  ModelBaseOfGuid:
    type: object
    properties:
      Id:
        type: string
        format: guid
      Name:
        type: string
  ListResponseOfTranscriptionProviderInstance:
    type: object
    properties:
      Results:
        type: array
        description: The list of results from the API call
        items:
          $ref: '#/definitions/TranscriptionProviderInstance'
  TranscriptionProviderInstanceSortFields:
    type: string
    description: ''
    x-enumNames:
    - Name
    enum:
    - Name
  SortOrder:
    type: string
    description: ''
    x-enumNames:
    - Asc
    - Desc
    enum:
    - Asc
    - Desc
  APIErrorInternal:
    type: object
    required:
    - Success
    properties:
      ErrorCode:
        type: string
        description: Internal error code
      Message:
        type: string
      Success:
        type: boolean
        description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
      ErrorSource:
        type: string
        description: Unique identifier of what caused this error
  APIError:
    type: object
    properties:
      Error:
        description: Error result returned if an error occurs in Panopto, otherwise null or missing
        $ref: '#/definitions/APIErrorInternal'
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
