openapi: 3.2.0
info:
  title: Panopto Public Playlists API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: Playlists
  description: Playlist API
paths:
  /api/v1/playlists/{id}:
    get:
      tags:
      - Playlists
      summary: Get a playlist by Id
      operationId: Playlists_GetPlaylistById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
        '404':
          description: The requested playlist was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    put:
      tags:
      - Playlists
      summary: Update a playlist
      description: Update the playlist's name, description, or folder.
      operationId: Playlists_UpdatePlaylistMetadata
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
        '404':
          description: The requested playlist was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaylistUpdate'
    delete:
      tags:
      - Playlists
      summary: Delete a playlist
      description: Deletes a playlist based on the retention policies
      operationId: Playlists_DeletePlaylist
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                format: guid
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
        '404':
          description: The requested playlist was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /api/v1/playlists/{id}/sessions:
    get:
      tags:
      - Playlists
      summary: Get a list of sessions in the given playlist
      description: 'To fetch all elements, this endpoint can be called multiple times, starting at pageNumber = 0 and incrementing the page number until no results are returned.


        **Note:** This endpoint does not return all available properties for a session. The CreatedBy and Urls properties (except the ViewerUrl and ThumbnailUrl) are not returned when searching for a session. To get these properties, you can get the specific session by Id.'
      operationId: Playlists_GetSessionsForPlaylist
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/PlaylistSessionSortFields'
        schema:
          type: string
          enum:
          - Name
          - CreatedDate
          - Relevance
          - Order
          default: Order
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        description: Page numbering starts at 0
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfSession'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
    put:
      tags:
      - Playlists
      summary: Add a session to a playlist
      description: Adds the given session to a playlist. You can optionally specify an index to insert the session at a specific position in the playlist. Otherwise, it will be added to the end of the playlist.
      operationId: Playlists_AddSessionToPlaylist
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfSession'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaylistAddSession'
  /api/v1/playlists:
    post:
      tags:
      - Playlists
      summary: Create a new playlist
      operationId: Playlists_CreatePlaylist
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaylistCreate'
  /api/v1/playlists/search:
    get:
      tags:
      - Playlists
      summary: Search for playlists based on a keyword
      description: 'To fetch all elements, this endpoint can be called multiple times, starting at pageNumber = 0 and incrementing the page number until no results are returned.


        **Note:** The Playlist Search API does not return all available properties for a playlist. The Urls property (except the ViewerUrl) is not returned when listing playlists in a folder. To get these properties, you can get the specific playlist by Id using the Playlists API.'
      operationId: Playlists_SearchForPlaylists
      parameters:
      - name: searchQuery
        in: query
        required: true
        schema:
          type: string
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/PlaylistSortFields'
        schema:
          type: string
          enum:
          - Name
          - CreatedDate
          - Relevance
          default: Name
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        description: Page numbering starts at 0
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfPlaylist'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
  /api/v1/playlists/{id}/sessions/{sessionId}:
    delete:
      tags:
      - Playlists
      summary: Remove a session from a playlist
      description: Removes the given session from a playlist.
      operationId: Playlists_RemoveSessionFromPlaylist
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      - name: sessionId
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
components:
  schemas:
    SessionUrls:
      type: object
      properties:
        ViewerUrl:
          type: string
          description: The URL to view this session in Panopto
        EmbedUrl:
          type: string
          description: The URL to an embedded version of this session
        ShareSettingsUrl:
          type: string
        DownloadUrl:
          type: string
          description: The URL to download this session. This URL is intended for one-time download only, and is not appropriate for direct streaming or playback. May be blank if not allowed.
        AudioDescriptionDownloadUrl:
          type: string
        CaptionDownloadUrl:
          type: string
          description: The URL to download captions for this session, if available.
        EditorUrl:
          type: string
          description: The URL to edit this session in Panopto, if you are a creator.
        ThumbnailUrl:
          type: string
          description: The URL to retrieve the thumbnail for this session
    PlaylistUrls:
      type: object
      properties:
        ViewerUrl:
          type: string
          description: The URL to view this playlist in Panopto
        EmbedUrl:
          type: string
          description: The URL to an embedded version of this playlist
        ThumbnailUrl:
          type: string
          description: The URL to retrieve the thumbnail for this playlist
    Session:
      type: object
      required:
      - Folder
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
        Description:
          type: string
        StartTime:
          type: string
          format: date-time
        Duration:
          type: number
          description: The duration of the session (in seconds)
          format: double
        MostRecentViewPosition:
          type: number
          format: double
        CreatedBy:
          $ref: '#/components/schemas/User'
        Urls:
          $ref: '#/components/schemas/SessionUrls'
        Folder:
          type: string
          format: guid
        FolderDetails:
          $ref: '#/components/schemas/BasicFolder'
        Context:
          type: array
          items:
            $ref: '#/components/schemas/SearchResultContext'
        PercentCompleted:
          type: integer
          description: The percentage from 0-100 of the session watched by the requested user
          format: int32
    PlaylistSortFields:
      type: string
      description: ''
      x-enumNames:
      - Name
      - CreatedDate
      - Relevance
      enum:
      - Name
      - CreatedDate
      - Relevance
    APIError:
      type: object
      properties:
        Error:
          description: Error result returned if an error occurs in Panopto, otherwise null or missing
          $ref: '#/components/schemas/APIErrorInternal'
    PlaylistSessionSortFields:
      type: string
      description: ''
      x-enumNames:
      - Name
      - CreatedDate
      - Relevance
      - Order
      enum:
      - Name
      - CreatedDate
      - Relevance
      - Order
    APIErrorInternal:
      type: object
      required:
      - Success
      properties:
        ErrorCode:
          type: string
          description: Internal error code
        Message:
          type: string
        Success:
          type: boolean
          description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
        ErrorSource:
          type: string
          description: Unique identifier of what caused this error
    Playlist:
      allOf:
      - $ref: '#/components/schemas/ModelBaseOfGuid'
      - type: object
        properties:
          Description:
            type: string
          Folder:
            $ref: '#/components/schemas/BasicFolder'
          Urls:
            $ref: '#/components/schemas/PlaylistUrls'
    ModelBaseOfGuid:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
    BasicFolder:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
    PlaylistAddSession:
      type: object
      required:
      - SessionId
      properties:
        SessionId:
          type: string
          description: The id of the session to add to this playlist.
          format: guid
        Index:
          type: integer
          description: The index to insert the item at (starting with 0 as the beginning of the list). If this is not specified, the session will be added to the end.
          format: int32
    User:
      type: object
      required:
      - Id
      properties:
        Id:
          type: string
          description: The id of the user.
          format: guid
        Username:
          type: string
          description: The username for this user.
    PlaylistCreate:
      type: object
      required:
      - FolderId
      properties:
        Name:
          type: string
          description: The name of the playlist.
        Description:
          type: string
          description: An optional description for the playlist.
        FolderId:
          type: string
          description: The folder to add this playlist to.
          format: guid
        Sessions:
          type: array
          description: A list of session IDs to add to this playlist. They will be added in order.
          items:
            type: string
            format: guid
    SortOrder:
      type: string
      description: ''
      x-enumNames:
      - Asc
      - Desc
      enum:
      - Asc
      - Desc
    ListResponseOfPlaylist:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/Playlist'
    ListResponseOfSession:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/Session'
    PlaylistUpdate:
      type: object
      properties:
        Name:
          type: string
          description: The new name for the playlist.
        Description:
          type: string
          description: The new description for the playlist.
        Folder:
          type: string
          description: The id of the folder to move this playlist to.
          format: guid
    SearchResultContext:
      type: object
      properties:
        Text:
          type: string
        Time:
          type: number
          format: double
        ThumbnailUrl:
          type: string
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
