openapi: 3.2.0
info:
  title: Panopto Public Users API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: Users
  description: User API
paths:
  /api/v1/users/me/sessions/viewed:
    get:
      tags:
      - Users
      summary: Get a list of partially viewed sessions for the current user
      operationId: Users_GetMyViewedSessions
      parameters:
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/SessionSortFields'
        schema:
          type: string
          enum:
          - Name
          - CreatedDate
          - Relevance
          default: Name
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        description: Page numbering starts at 0
        schema:
          type: integer
          format: int32
          default: 0
      - name: includeCompleted
        in: query
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfSession'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
        '404':
          description: The requested user was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /api/v1/users/{id}/sessions/viewed:
    get:
      tags:
      - Users
      summary: Get a list of partially viewed sessions for the specified user
      description: This endpoint can only be called by an admin
      operationId: Users_GetUsersViewedSessions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/SessionSortFields'
        schema:
          type: string
          enum:
          - Name
          - CreatedDate
          - Relevance
          default: Name
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        description: Page numbering starts at 0
        schema:
          type: integer
          format: int32
          default: 0
      - name: includeCompleted
        in: query
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfSession'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
        '404':
          description: The requested user was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /api/v1/users/search:
    get:
      tags:
      - Users
      summary: Search for users based on a keyword
      operationId: Users_Search
      parameters:
      - name: searchQuery
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfUser'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
components:
  schemas:
    SessionUrls:
      type: object
      properties:
        ViewerUrl:
          type: string
          description: The URL to view this session in Panopto
        EmbedUrl:
          type: string
          description: The URL to an embedded version of this session
        ShareSettingsUrl:
          type: string
        DownloadUrl:
          type: string
          description: The URL to download this session. This URL is intended for one-time download only, and is not appropriate for direct streaming or playback. May be blank if not allowed.
        AudioDescriptionDownloadUrl:
          type: string
        CaptionDownloadUrl:
          type: string
          description: The URL to download captions for this session, if available.
        EditorUrl:
          type: string
          description: The URL to edit this session in Panopto, if you are a creator.
        ThumbnailUrl:
          type: string
          description: The URL to retrieve the thumbnail for this session
    APIError:
      type: object
      properties:
        Error:
          description: Error result returned if an error occurs in Panopto, otherwise null or missing
          $ref: '#/components/schemas/APIErrorInternal'
    Session:
      type: object
      required:
      - Folder
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
        Description:
          type: string
        StartTime:
          type: string
          format: date-time
        Duration:
          type: number
          description: The duration of the session (in seconds)
          format: double
        MostRecentViewPosition:
          type: number
          format: double
        CreatedBy:
          $ref: '#/components/schemas/User'
        Urls:
          $ref: '#/components/schemas/SessionUrls'
        Folder:
          type: string
          format: guid
        FolderDetails:
          $ref: '#/components/schemas/BasicFolder'
        Context:
          type: array
          items:
            $ref: '#/components/schemas/SearchResultContext'
        PercentCompleted:
          type: integer
          description: The percentage from 0-100 of the session watched by the requested user
          format: int32
    APIErrorInternal:
      type: object
      required:
      - Success
      properties:
        ErrorCode:
          type: string
          description: Internal error code
        Message:
          type: string
        Success:
          type: boolean
          description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
        ErrorSource:
          type: string
          description: Unique identifier of what caused this error
    ListResponseOfUser:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/User'
    BasicFolder:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
    SessionSortFields:
      type: string
      description: ''
      x-enumNames:
      - Name
      - CreatedDate
      - Relevance
      enum:
      - Name
      - CreatedDate
      - Relevance
    User:
      type: object
      required:
      - Id
      properties:
        Id:
          type: string
          description: The id of the user.
          format: guid
        Username:
          type: string
          description: The username for this user.
    SortOrder:
      type: string
      description: ''
      x-enumNames:
      - Asc
      - Desc
      enum:
      - Asc
      - Desc
    ListResponseOfSession:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/Session'
    SearchResultContext:
      type: object
      properties:
        Text:
          type: string
        Time:
          type: number
          format: double
        ThumbnailUrl:
          type: string
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
