openapi: 3.2.0
info:
  title: Panopto Public Tags API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: Tags
  description: Tag API
paths:
  /api/v1/tags:
    post:
      tags:
      - Tags
      summary: Create a new tag
      description: Create a new tag with the provided content.
      operationId: Tags_CreateTag
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function.
        '401':
          description: The user is not authorized to perform the requested action.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
    get:
      tags:
      - Tags
      summary: Get a paged list of tags
      description: To fetch all elements, this endpoint can be called multiple times, starting at pageNumber = 0 and incrementing the page number until no results are returned.
      operationId: Tags_GetTags
      parameters:
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/TagSortFields'
        schema:
          type: string
          enum:
          - CreateDate
          - UsageCount
          - Content
          - Creator
          - MostRecentUseDate
          default: CreateDate
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfTag'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function.
        '401':
          description: The user is not authorized to perform the requested action.
  /api/v1/tags/{id}:
    get:
      tags:
      - Tags
      summary: Get a tag by ID
      operationId: Tags_GetTagById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function.
        '401':
          description: The user is not authorized to perform the requested action.
        '404':
          description: The requested tag was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    put:
      tags:
      - Tags
      summary: Update a tag
      description: Update the tag's content.
      operationId: Tags_UpdateTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function.
        '401':
          description: The user is not authorized to perform the requested action.
        '404':
          description: The requested tag was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdate'
    delete:
      tags:
      - Tags
      summary: Delete a tag
      description: Delete the tag with the given ID.
      operationId: Tags_DeleteTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                format: guid
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
  /api/v1/tags/{id}/merge:
    post:
      tags:
      - Tags
      summary: Merge one or more tags into the tag represented by {id}
      description: This will delete the merged tags and update videos to reference the tag represented by {id}.
      operationId: Tags_MergeTags
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
        '404':
          description: The requested tag was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagMerge'
components:
  schemas:
    APIError:
      type: object
      properties:
        Error:
          description: Error result returned if an error occurs in Panopto, otherwise null or missing
          $ref: '#/components/schemas/APIErrorInternal'
    APIErrorInternal:
      type: object
      required:
      - Success
      properties:
        ErrorCode:
          type: string
          description: Internal error code
        Message:
          type: string
        Success:
          type: boolean
          description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
        ErrorSource:
          type: string
          description: Unique identifier of what caused this error
    User:
      type: object
      required:
      - Id
      properties:
        Id:
          type: string
          description: The id of the user.
          format: guid
        Username:
          type: string
          description: The username for this user.
    TagMerge:
      type: object
      properties:
        TagIdsToMerge:
          type: array
          description: The IDs of the tags that should be merged and then deleted.
          items:
            type: string
            format: guid
    TagSortFields:
      type: string
      description: ''
      x-enumNames:
      - CreateDate
      - UsageCount
      - Content
      - Creator
      - MostRecentUseDate
      enum:
      - CreateDate
      - UsageCount
      - Content
      - Creator
      - MostRecentUseDate
    TagUpdate:
      allOf:
      - $ref: '#/components/schemas/TagCreate'
      - type: object
    SortOrder:
      type: string
      description: ''
      x-enumNames:
      - Asc
      - Desc
      enum:
      - Asc
      - Desc
    ListResponseOfTag:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/Tag'
    Tag:
      type: object
      required:
      - UsageCount
      - CreateDate
      properties:
        Id:
          type: string
          format: guid
        Content:
          type: string
        UsageCount:
          type: integer
          format: int64
        CreateDate:
          type: string
          format: date-time
        MostRecentUseDate:
          type: string
          format: date-time
        CreatedBy:
          $ref: '#/components/schemas/User'
    TagCreate:
      type: object
      properties:
        Content:
          type: string
          description: The content of the tag.
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
