openapi: 3.2.0
info:
  title: Panopto Public Search Index Sync Updates API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: SearchIndexSyncUpdates
  description: Search Index Integration API
paths:
  /api/v1/searchIndexSync/updates:
    get:
      tags:
      - SearchIndexSyncUpdates
      summary: Get IDs for videos and playlists updated after a specified UTC date time
      operationId: SearchIndexSyncUpdates_GetUpdates
      parameters:
      - name: fromDate
        in: query
        required: true
        schema:
          type: string
          format: date-time
      - name: nextToken
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchIndexSyncUpdateResponse'
  /api/v1/searchIndexSync/content:
    get:
      tags:
      - SearchIndexSyncUpdates
      summary: Get the content for Search Index Integration for a video or playlist by ID
      operationId: SearchIndexSyncUpdates_GetContent
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchIndexSyncContentResponse'
components:
  schemas:
    SearchIndexSyncUpdateResponse:
      allOf:
      - $ref: '#/components/schemas/ModelBase'
      - type: object
    SearchIndexSyncContentResponse:
      allOf:
      - $ref: '#/components/schemas/ModelBase'
      - type: object
    ModelBase:
      type: object
      properties:
        Id:
          type: string
          description: The unique identifier for this item.
          format: guid
        Name:
          type: string
          description: The name of this item.
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
