openapi: 3.2.0
info:
  title: Panopto Public Groups API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: Groups
  description: Group API
paths:
  /api/v1/groups/search:
    get:
      tags:
      - Groups
      summary: Search for groups based on a keyword
      operationId: Groups_Search
      parameters:
      - name: searchQuery
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfGroup'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
components:
  schemas:
    APIError:
      type: object
      properties:
        Error:
          description: Error result returned if an error occurs in Panopto, otherwise null or missing
          $ref: '#/components/schemas/APIErrorInternal'
    ListResponseOfGroup:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/Group'
    APIErrorInternal:
      type: object
      required:
      - Success
      properties:
        ErrorCode:
          type: string
          description: Internal error code
        Message:
          type: string
        Success:
          type: boolean
          description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
        ErrorSource:
          type: string
          description: Unique identifier of what caused this error
    Group:
      allOf:
      - $ref: '#/components/schemas/ModelBaseOfGuid'
      - type: object
    ModelBaseOfGuid:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
