openapi: 3.2.0
info:
  title: Panopto Public Caption Providers API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: CaptionProviders
  description: Caption Providers API
paths:
  /api/v1/captionproviders:
    get:
      tags:
      - CaptionProviders
      summary: Get caption providers
      description: To fetch all elements, this endpoint can be called multiple times, starting at pageNumber = 0 and incrementing the page number until no results are returned.
      operationId: CaptionProviders_GetCaptionProviders
      parameters:
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/TranscriptionProviderInstanceSortFields'
        schema:
          type: string
          enum:
          - Name
          default: Name
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfTranscriptionProviderInstance'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
components:
  schemas:
    APIError:
      type: object
      properties:
        Error:
          description: Error result returned if an error occurs in Panopto, otherwise null or missing
          $ref: '#/components/schemas/APIErrorInternal'
    APIErrorInternal:
      type: object
      required:
      - Success
      properties:
        ErrorCode:
          type: string
          description: Internal error code
        Message:
          type: string
        Success:
          type: boolean
          description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
        ErrorSource:
          type: string
          description: Unique identifier of what caused this error
    TranscriptionProviderInstanceSortFields:
      type: string
      description: ''
      x-enumNames:
      - Name
      enum:
      - Name
    SortOrder:
      type: string
      description: ''
      x-enumNames:
      - Asc
      - Desc
      enum:
      - Asc
      - Desc
    TranscriptionProviderInstance:
      allOf:
      - $ref: '#/components/schemas/ModelBaseOfGuid'
      - type: object
        required:
        - Enabled
        properties:
          Enabled:
            type: boolean
          DisplayName:
            type: string
    ListResponseOfTranscriptionProviderInstance:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/TranscriptionProviderInstance'
    ModelBaseOfGuid:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
