openapi: 3.2.0
info:
  title: Panopto Public Remote Recorders API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: RemoteRecorders
  description: Remote Recorder Management API
paths:
  /api/v1/remoteRecorders/search:
    get:
      tags:
      - RemoteRecorders
      summary: Search for remote recorders based on a keyword
      description: To fetch all elements, this endpoint can be called multiple times, starting at pageNumber = 0 and incrementing the page number until no results are returned.
      operationId: RemoteRecorders_SearchForRemoteRecorders
      parameters:
      - name: searchQuery
        in: query
        required: true
        schema:
          type: string
      - name: sortField
        in: query
        x-schema:
          $ref: '#/components/schemas/RemoteRecorderSortFields'
        schema:
          type: string
          enum:
          - Name
          default: Name
      - name: sortOrder
        in: query
        x-schema:
          $ref: '#/components/schemas/SortOrder'
        schema:
          type: string
          enum:
          - Asc
          - Desc
          default: Asc
      - name: pageNumber
        in: query
        description: Page numbering starts at 0
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseOfRemoteRecorder'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: User does not have permission to access this function
        '401':
          description: The user is not authorized to perform the requested action
components:
  schemas:
    APIError:
      type: object
      properties:
        Error:
          description: Error result returned if an error occurs in Panopto, otherwise null or missing
          $ref: '#/components/schemas/APIErrorInternal'
    APIErrorInternal:
      type: object
      required:
      - Success
      properties:
        ErrorCode:
          type: string
          description: Internal error code
        Message:
          type: string
        Success:
          type: boolean
          description: If true the call succeed and this is a partial failure (or warning). If false the call failed overall
        ErrorSource:
          type: string
          description: Unique identifier of what caused this error
    BasicFolder:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
    RemoteRecorderState:
      type: string
      description: ''
      x-enumNames:
      - Stopped
      - Previewing
      - Recording
      - Paused
      - Faulted
      - Disconnected
      - RecorderRunning
      enum:
      - Stopped
      - Previewing
      - Recording
      - Paused
      - Faulted
      - Disconnected
      - RecorderRunning
    RemoteRecorderSortFields:
      type: string
      description: ''
      x-enumNames:
      - Name
      enum:
      - Name
    RemoteRecorder:
      type: object
      required:
      - State
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
        State:
          $ref: '#/components/schemas/RemoteRecorderState'
        DefaultRecordingFolder:
          $ref: '#/components/schemas/BasicFolder'
    SortOrder:
      type: string
      description: ''
      x-enumNames:
      - Asc
      - Desc
      enum:
      - Asc
      - Desc
    ListResponseOfRemoteRecorder:
      type: object
      properties:
        Results:
          type: array
          description: The list of results from the API call
          items:
            $ref: '#/components/schemas/RemoteRecorder'
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
