openapi: 3.2.0
info:
  title: Panopto Public Xfp User Profiles API
  description: The public API for Panopto. OpenID & OAuth information can be found at Panopto/oauth2/.well-known/openid-configuration
  version: '1'
servers:
- url: https://<PanoptoServerURL>(i.e. example.hosted.panopto.com)/Panopto
tags:
- name: XfpUserProfiles
  description: Portals API
paths:
  /api/v1/portal/{portalId}/user:
    post:
      tags:
      - XfpUserProfiles
      summary: Create XFP user profile
      operationId: XfpUserProfiles_Create
      parameters:
      - name: portalId
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: Created user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XfpUserProfile'
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized access
        '412':
          description: Precondition failed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XfpUserProfileCreate'
    get:
      tags:
      - XfpUserProfiles
      summary: Get XFP user profiles according to the filter
      operationId: XfpUserProfiles_List
      parameters:
      - name: portalId
        in: path
        required: true
        schema:
          type: string
          format: guid
      - name: XfpRole
        in: query
        schema:
          type: string
      - name: EmailAddress
        in: query
        schema:
          type: string
      - name: Page
        in: query
        schema:
          type: integer
          format: int32
      - name: PageSize
        in: query
        schema:
          type: integer
          format: int32
      - name: Sort
        in: query
        schema:
          type: string
      - name: SecondarySort
        in: query
        schema:
          type: string
      - name: SortDescending
        in: query
        schema:
          type: boolean
      - name: SecondarySortDescending
        in: query
        schema:
          type: boolean
      - name: ComputeTotalCount
        in: query
        schema:
          type: boolean
      - name: ComputeHasMorePages
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XfpUserProfile'
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized access
  /api/v1/portal/{portalId}/user/{userId}:
    delete:
      tags:
      - XfpUserProfiles
      summary: Delete an XFP user profile
      operationId: XfpUserProfiles_Delete
      parameters:
      - name: portalId
        in: path
        required: true
        schema:
          type: string
          format: guid
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: If xfp user was deleted successfully
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized access
        '412':
          description: Precondition failed
        '404':
          description: XFP user profile not found
    put:
      tags:
      - XfpUserProfiles
      summary: Update an XFP user profile
      operationId: XfpUserProfiles_Update
      parameters:
      - name: portalId
        in: path
        required: true
        schema:
          type: string
          format: guid
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: Updated user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XfpUserProfile'
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized access
        '412':
          description: Precondition failed
        '404':
          description: XFP user profile not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XfpUserProfileUpdate'
  /api/v1/portal/{portalId}/user/bulk-create:
    post:
      tags:
      - XfpUserProfiles
      summary: Bulk Create XFP users
      operationId: XfpUserProfiles_BulkCreate
      parameters:
      - name: portalId
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XfpUserProfile'
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized access
  /api/v1/portal/{portalId}/user/bulk-delete:
    post:
      tags:
      - XfpUserProfiles
      summary: Bulk Delete XFP users
      operationId: XfpUserProfiles_BulkDelete
      parameters:
      - name: portalId
        in: path
        required: true
        schema:
          type: string
          format: guid
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XfpUserProfile'
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized access
components:
  schemas:
    XfpUserProfileCreate:
      type: object
      required:
      - XfpRole
      properties:
        FirstName:
          type: string
        LastName:
          type: string
        EmailAddress:
          type: string
        XfpRole:
          $ref: '#/components/schemas/XfpUserRole'
        TemporaryPassword:
          type: string
    XfpUserProfile:
      allOf:
      - $ref: '#/components/schemas/ModelBaseOfGuid'
      - type: object
        required:
        - UserId
        - PortalPublicId
        - CreatedDate
        properties:
          UserId:
            type: string
            format: guid
          FirstName:
            type: string
          LastName:
            type: string
          EmailAddress:
            type: string
          PortalPublicId:
            type: string
            format: guid
          XfpRole:
            type: string
          CreatedDate:
            type: string
            format: date-time
    XfpUserRole:
      type: string
      description: ''
      x-enumNames:
      - Viewer
      - PortalManager
      enum:
      - Viewer
      - PortalManager
    XfpUserProfileUpdate:
      type: object
      properties:
        XfpRole:
          type: string
        FirstName:
          type: string
        LastName:
          type: string
    ModelBaseOfGuid:
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
